// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'firebase_options.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDisiPq6-efh788rDz9Pz9gt4JWpyJf5pU',
    appId: '1:1038330628156:web:94c81c185b26097a6f5b39',
    messagingSenderId: '1038330628156',
    projectId: 'joseph-d-pictionis',
    authDomain: 'joseph-d-pictionis.firebaseapp.com',
    storageBucket: 'joseph-d-pictionis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBht052y1bWjS3FMFsi1hs6n5cXyP3_CZ8',
    appId: '1:1038330628156:android:af1eb2a0262aa6326f5b39',
    messagingSenderId: '1038330628156',
    projectId: 'joseph-d-pictionis',
    storageBucket: 'joseph-d-pictionis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR958DdGDFgai2iusOccPQqdKGl5OaR60',
    appId: '1:1038330628156:ios:7f0a2e70fd65f4b96f5b39',
    messagingSenderId: '1038330628156',
    projectId: 'joseph-d-pictionis',
    storageBucket: 'joseph-d-pictionis.appspot.com',
    iosBundleId: 'com.example.myPic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR958DdGDFgai2iusOccPQqdKGl5OaR60',
    appId: '1:1038330628156:ios:47b54abfc593e2356f5b39',
    messagingSenderId: '1038330628156',
    projectId: 'joseph-d-pictionis',
    storageBucket: 'joseph-d-pictionis.appspot.com',
    iosBundleId: 'com.example.myPic.RunnerTests',
  );
}
